# Generated by Django 3.0.4 on 2020-04-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200406_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
