# Generated by Django 3.0.4 on 2020-04-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200408_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='photo',
            field=models.URLField(),
        ),
    ]
