# Generated by Django 3.0.4 on 2020-04-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200408_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
