# Generated by Django 3.0.4 on 2020-04-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200409_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=55)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('phone', models.BigIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
